<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1a1a1a; font-size: 13px; }
        .header { text-align: center; border-bottom: 3px solid #1F573D; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { margin: 0; color: #1F573D; font-size: 20px; }
        .header p { margin: 4px 0 0; color: #555; }
        .title { text-align: center; font-size: 18px; font-weight: bold; margin: 24px 0; text-transform: uppercase; letter-spacing: 1px; }
        .meta { width: 100%; margin-bottom: 20px; }
        .meta td { padding: 4px 0; font-size: 13px; }
        .meta td.label { color: #666; width: 160px; }
        .body-text { line-height: 1.7; margin: 24px 0; }
        .signature { margin-top: 60px; width: 100%; }
        .signature td { width: 50%; text-align: center; padding-top: 40px; border-top: 1px solid #333; font-size: 12px; }
        .footer { margin-top: 40px; font-size: 10px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Yangon Adventist Seminary</h1>
        <p>34, Natmauk Lane (1), Bocho Ward (2), Bahan Township, Bahan PO 11201, Yangon, Myanmar</p>
    </div>

    <div class="title">{{ $doc->type }}</div>

    <table class="meta">
        <tr><td class="label">Student ID</td><td>{{ $doc->student->student_id_number }}</td></tr>
        <tr><td class="label">Student Name</td><td>{{ $doc->student->name }}</td></tr>
        <tr><td class="label">Department</td><td>{{ $doc->student->department->name ?? '—' }}</td></tr>
        <tr><td class="label">Admission Date</td><td>{{ $doc->student->admission_date->format('F j, Y') }}</td></tr>
        <tr><td class="label">Document Date</td><td>{{ now()->format('F j, Y') }}</td></tr>
    </table>

    <div class="body-text">
        @switch($doc->type)
            @case('Transfer/Leaving Certificate')
                This is to certify that <strong>{{ $doc->student->name }}</strong>
                (Student ID: {{ $doc->student->student_id_number }}) was a bona fide student of Yangon Adventist Seminary
                and has been transferred / has left the institution as of the date of this certificate. This certificate
                is issued upon request for the purpose of transfer to another institution.
                @break

            @case('Completion Certificate')
                This is to certify that <strong>{{ $doc->student->name }}</strong>
                (Student ID: {{ $doc->student->student_id_number }}) has successfully completed the required course of
                study at Yangon Adventist Seminary and has been marked as graduated from the {{ $doc->student->department->name ?? '' }}
                department. This certificate is issued in recognition of that achievement.
                @break

            @case('Enrollment Certificate')
                This is to certify that <strong>{{ $doc->student->name }}</strong>
                (Student ID: {{ $doc->student->student_id_number }}) is currently a bona fide, enrolled student of
                Yangon Adventist Seminary in the {{ $doc->student->department->name ?? '' }} department. This certificate
                is issued upon request for official purposes.
                @break

            @default
                <em>Academic record for this document will populate once grades are entered through the Examination &amp;
                Grading module (a later implementation phase). This is a placeholder draft.</em>
        @endswitch
    </div>

    <table class="signature">
        <tr>
            <td>Registrar</td>
            <td>Principal</td>
        </tr>
    </table>

    <div class="footer">
        Generated by the ISMS on {{ now()->format('F j, Y \a\t H:i') }} · Document #{{ $doc->id }} ·
        Physical institutional seal and signature required for legal validity.
    </div>
</body>
</html>
